### ISSUE TITLE
Permissions not inheriting

### ISSUE THREAD

**Issue by bigteejay** [composer/docker#67] opened 2018-11-30 20:10 UTC
I dont know if the issue I am encountering is related to [this](https://github.com/composer/docker/issues/30) or not.

I have a Dockerfile in which I ensure a path I want composer to install packages to has the needed permissions (specifically, that it is [writable](https://userguide.taotesting.com/3.2/introduction/installing-tao.html)).  However, rather than inheriting the permissions (with +s set), everything composer installs is read-only.  Adjusting the Dockerfile to then go back and manually make things writable extends build times significantly (I killed it off at 20mins last time.)

Any idea as to what might be preventing the permissions from inheriting?  Ideas for a viable workaround?

**Comment by alcohol** [comment] 2018-11-30 23:59
Not a clue unless you can provide me/us with a reproducible scenario :-)

**Comment by bigteejay** [comment] 2018-12-01 00:12
Completely fair.  I'll see if I can mock up a repro shortly.

**Comment by alcohol** [comment] 2018-12-03 06:55
Your mount completely invalidates the preparations you make in your container.

The first time you spin up your container using `docker-compose`, the named `src` volume will be created and owned by `root`. It will be mounted on top of `/var/www/html`. It will not inherit any of the permissions and such you set on it in your `Dockerfile`.

**Comment by bigteejay** [comment] 2018-12-03 23:49
But it is mounted `rw`?

Also, why then does the parent (`$BUILD_PATH`) directory retain its permissions as defined in the Dockerfile (namely, `u+w,g+w`)?

**Comment by alcohol** [comment] 2018-12-04 08:09
I'm just commenting on your example. You prepare a directory with certain permissions and such, and then you overlap a mount on top of it, creating a whole new directory structure basically. So I am not sure what you are expecting. The directory in the Dockerfile is not the same as you will have in the volume mount.

**Comment by bigteejay** [comment] 2018-12-04 19:09
Understood.  I appreciate any feedback (relatively new to docker).  That being said, it works as needed if I force +w in the image and mount as rw.  I am just trying to figure out why the extra work is necessary and permissions arent just inherited from the parent folder.

**Comment by alcohol** [comment] 2018-12-05 10:07
I am rather confused as to what the problem is though. You say everything Composer installs is read-only. But what is 'everything'?

By default, the `vendor` directory (and all subdirectories) will be `755` and files will be `644`, unless the original package explicitly maintains different permissions (those should be respected in most cases, especially since https://github.com/composer/docker/commit/5f82e6f3af987a33ed53fd90f93452d64f9e16b1).

These permissions are very suitable for almost all cases. If you want Composer to use different permissions though, you should probably just set a different `umask` before running Composer.

For example:
```
$ umask 0000
$ composer require ...
...
```
This will create directories with 777 permissions and files with 666.

**Comment by bigteejay** [comment] 2018-12-06 22:45
"Everything" = the files in that image path (eg: `/var/www/html`) that are *only* present after build when the `RUN composer install...` line is *NOT* ccommented out.

(Still reviewing the rest of your feedback, just wanted to clarify that portion)

**Comment by bigteejay** [comment] 2018-12-06 22:56
Neither `755` nor `644` would be usable for my needs (as the application requires write permissions to the folder structure created by `composer install ...`, hence why my `Dockerfile` specifies `+w`)

Ah-ha!  I am not familiar with `umask`, but that looks **very** promising (thanks)!  I'll investigate using that tomorrow and see how it goes and let you know.

**Comment by bigteejay** [comment] 2018-12-08 02:16
I changed the Dockerfile to...

````
FROM composer

ARG BUILD_PATH=/var/www/html
RUN echo "NOTE: Using ${BUILD_PATH} for build path"
RUN umask u+rwx,g+rwx \
    && mkdir -p ${BUILD_PATH} && cd ${BUILD_PATH} \
    && chown root:www-data ${BUILD_PATH}
WORKDIR ${BUILD_PATH}

ARG TAO_CODE_TAG=v3.2-rc02
ADD --chown=root:www-data https://cdn.jsdelivr.net/gh/oat-sa/package-tao@${TAO_CODE_TAG}/composer.json ${BUILD_PATH}/composer.json

RUN composer install --ignore-platform-reqs --no-scripts --no-suggest --no-dev

RUN chown -R root:www-data ${BUILD_PATH}

# Don't attempt to install via composer again, just exit
ENTRYPOINT 'sh'
CMD ''
````
...but upon checking the outcome within the built image, the permissions are correct for the parent `/var/www/html/`, but still incorrect (no `+w`) for the contents therein.

Am I using it incorrectly?

**Comment by bigteejay** [comment] 2018-12-08 02:19
Interestingly, `docker run`ing into the created image, and just running `umask` yields `0022` as the current default (which seems unexpected?)

**Comment by jaapio** [comment] 2019-01-27 16:16
I use this wrapper script to run the composer image:

```
#!/bin/bash

composer () {
    tty=
    tty -s && tty=--tty
    docker run \
        $tty \
        --interactive \
        --rm \
        --user $(id -u):$(id -g) \
        --volume $SSH_AUTH_SOCK:/ssh-auth.sock \
        --volume /etc/passwd:/etc/passwd:ro \
        --volume /etc/group:/etc/group:ro \
        --volume $HOME/.composer:/composer \
        --volume $(pwd):/app \
        --env SSH_AUTH_SOCK=/ssh-auth.sock \
        --env COMPOSER_HOME=/composer \
        --env APP_ENV=$APP_ENV \
        composer "$@"
}

composer "$@"
```
Using the `--user` param of docker you can specify running as a different user. Since linux is just using user id's and not usernames there is no need to create a user.

**Comment by alcohol** [comment] 2020-07-22 08:57
Closing this issue because there has not been any activity on it in a long time.

**Closed by alcohol** 2020-07-22 08:57 UTC
